atoma-network/atoma-node

Cargo.toml
atoma-inference/src/model_thread.rs
atoma-inference/src/models/candle/flux.rs
atoma-inference/src/models/candle/llama.rs
atoma-inference/src/models/candle/mod.rs
atoma-inference/src/models/mod.rs
atoma-inference/src/models/types.rs
atoma-types/src/lib.rs

We aim to expand our model offerings by integrating the Flux model, which provides advanced text-to-image generation capabilities. Additionally, we're updating dependencies to ensure compatibility and leverage the latest features.
This PR introduces the following changes:
1. Added support for the Flux model, including both Dev and Schnell variants.
2. Implemented new structures and methods to handle Flux model input, output, and processing.
3. Updated the `cudarc` dependency to version 0.12.0.
4. Modified existing model handling code to accommodate the new Flux model.
5. Enhanced the `Text2ImagePromptParams` struct with new fields and methods.
6. Updated various enums and implementations to include Flux-related options.
Key additions:
- New `flux.rs` file containing Flux model …

feat: add flux model

---

atoma-state/src/state_manager.rs

Rename the indexes to conventional naming to prevent collisions.

fix: rename the db indexes to conventional naming

---

atoma-bin/atoma_daemon.rs
atoma-sui/src/client.rs

Add `new_from_config` to `AtomaSuiClient` and change the new to take config as a parameter. So it's the same as other structs that we have in this repo.

feat: add new_from_config to AtomaSuiClient

---

atoma-sui/src/client.rs

Remove the page size. If `None` is provided, it will use the max available from the sdk. Which currently is 50. So I'm getting : `RpcError(Call(Custom(ErrorObject { code: InvalidParams, message: "Page size limit 100 exceeds max limit 50", data: None })))`
So lets just let the sdk use the max.

fix: remove page size for cursor

---

atoma-daemon/src/config.rs
atoma-service/src/config.rs
atoma-state/src/config.rs
atoma-sui/src/config.rs
config.example.toml

Add the possibility to override config values from env vars.
E.g.  in the config
```
[atoma_daemon]
service_bind_address
```
can be overwritten with setting `ATOMA_DAEMON__SERVICE_BIND_ADDRESS` (mind the double _ between ATOMA_DAEMON and the rest.
After merging this, change your local config.toml. The section names are changing from dash to underscore, e.g. `atoma-daemon` to `atoma_daemon`

feat: add the option to override config from env vars

---

atoma-state/src/handlers.rs
atoma-sui/src/events.rs
atoma-sui/src/subscriber.rs

Add sender to node subscription event. This way we can check signatures on other messages that claims to be from this node (e.g. update node public address )

feat: add sender to node subscription event

---

Cargo.lock
atoma-service/Cargo.toml
atoma-service/src/middleware.rs
atoma-utils/Cargo.toml
atoma-utils/src/lib.rs

Move the signature verification to atoma-utils, so it can be reused in atoma-proxy

chore: move verify signature to atoma-utils

---

atoma-bin/atoma_node.rs
atoma-service/src/lib.rs
atoma-service/src/proxy/config.rs
atoma-service/src/proxy/mod.rs
atoma-service/src/server.rs
config.example.toml

Add config settings for the proxy where we want to register. Added the `proxy_server` section
- `proxy_address` address of the proxy where to send the registration
- `node_public_address` that's our address where the proxy can send http requests
- `country` the country of this node (this will be removed if we can get this information from the `node_public_address`
The registration is signed with the sui keystore (don't forget to set the `-a` index when testing locally with more than one sui address)

feat: register on proxy

---

Cargo.lock
Cargo.toml

Previous versions of `tokenizers` were not compatible with `Llama-3.3-70B-Instruct`'s model tokenizer.json

feat: update tokenizers version

---

.github/workflows/ci.yml

To prevent a recurrence of the linting errors that https://github.com/atoma-network/atoma-node/pull/350 addresses

ci: update ci job to catch lint errors

---

.github/dependabot.yml

We currently want to update these deps manually if we choose to do so until we have more solid end-to-end tests

ci: add some dependencies to be ignored

---

Cargo.lock
Cargo.toml

Our security audit detected [a vulnerability](https://github.com/atoma-network/atoma-node/actions/runs/12998894498/job/36253012065) in `rustls` which is a transitive dependency. 
This applies a patch for it.
The other current [RSA timing vulnerability](https://rustsec.org/advisories/RUSTSEC-2023-0071.html)  is currently unpatched but doesn't apply to us.

build: fix issue related to rustls audit

---

atoma-service/docs/openapi.yml
atoma-service/src/handlers/chat_completions.rs
atoma-service/src/middleware.rs

Deprecate the use of `max_tokens` to `max_completion_tokens`, following OpenAI's API spec

feat: deprecate the use of max_tokens to max_completion_tokens, following openai api spec

---

.github/workflows/e2e.yml

In order to run these tests manually I've configured it to run on the `workflow_dispatch` event.
For more info see https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow

ci: add workflow dispatch for e2e tests

---

README.md
docker-compose.yaml

A user can now run 
```console
export PLATFORM=linux/amd64
```
Then 
```console
COMPOSE_PROFILES=mistralrs-cpu,non-confidential docker compose up -d
```
This builds off the fixes in https://github.com/atoma-network/atoma-node/pull/409

build: allow for `linux/amd64` profiles on docker builds

---

docker-compose.dev.yaml

Related to https://github.com/atoma-network/atoma-proxy/pull/243
We don't need volumes for short-lived environments

build: remove unnecessary volumes from dev compose

---

Dockerfile

I've also upgraded the rust toolchain to `1.84.0`

ci: migrate to ubuntu for builds

---

.env.example
docker-compose.dev.yaml

This is needed for https://github.com/atoma-network/atoma-testground

build: add internal port for CI runs

---

Cargo.lock
Cargo.toml
atoma-daemon/Cargo.toml
atoma-p2p/Cargo.toml
atoma-p2p/src/errors.rs
atoma-p2p/src/lib.rs
atoma-p2p/src/metrics.rs
atoma-p2p/src/service.rs
atoma-p2p/src/tests.rs
atoma-p2p/src/timer.rs
atoma-p2p/src/types.rs
atoma-p2p/src/utils.rs
atoma-service/Cargo.toml
deny.toml

- Closes #432 
- Closes #416 
Related to  #410

feat: add initial metrics for p2p comms

---

Cargo.lock
Cargo.toml
atoma-bin/atoma_daemon.rs
atoma-bin/atoma_node.rs
atoma-daemon/src/lib.rs
atoma-daemon/src/telemetry.rs
atoma-p2p-tester/.gitignore
atoma-p2p-tester/Cargo.toml
atoma-p2p-tester/Dockerfile
atoma-p2p-tester/docker-compose.yml
atoma-p2p-tester/src/main.rs
atoma-p2p/Cargo.toml
atoma-p2p/src/config.rs
atoma-p2p/src/errors.rs
atoma-p2p/src/service.rs
config.example.toml
docker-compose.test.yaml

This PR creates a crate that will be used solely for testing the p2p-related functionality of the node, particularly the gossipsub metrics and health.
It also includes some fixes for connecting to bootstrap nodes and some fixes for `mdns`

feat: add p2p tester crate

---

Cargo.lock
atoma-sui/src/client.rs

This PR fixes an issue in extracting the key_rotation_counter and nonce fields from the object.fields JSON representation.
1. Corrected the extraction logic to first attempt parsing values as u64 and then as str before converting to u64.
2. Fixed redundant .and_then() chaining that could cause incorrect parsing behavior.
3. Ensured both key_rotation_counter and nonce are correctly extracted before returning them.
1. Previously, the extraction attempted .as_u64() before .as_str(), which would always fail for string-encoded numbers. 
2. This PR corrects the order to properly handle string representations.
Verified correct parsing behavior with different JSON inputs.
This fix ensures robust parsing of key rotation counters and nonces, preventing potential failures in cryptographic operations …

feat: address parsing of key rotation counter and nonce in `get_last_key_rotation_event`

---

atoma-p2p/src/config.rs
atoma-p2p/src/service.rs
config.example.toml
docker-compose.yaml

Map `local key` file from config.
Don't map files in `docker-compose.yml`
Change example config to use paths in the docker mapped folder `/app/data` instead of `./`

feat: local key path from config

---

.github/workflows/audit.yml

Similarly to https://github.com/atoma-network/atoma-proxy/pull/329  ignoring these until https://github.com/MystenLabs/sui-rust-sdk/issues/107 is resolved

ci: add Sui related security alerts to audit ignore

---

README.md
docker-compose.yaml

This will allow us to run without the `nvidia` runtime for our e2e tests as orchestrated in https://github.com/atoma-network/atoma-testground/pull/17
I've also updated the `README.md` to reflect the reality that we always run in confidential mode.

build: allow for non-nvidia runtime builds

---

Cargo.lock
atoma-service/src/handlers/chat_completions.rs
atoma-service/src/handlers/embeddings.rs
atoma-service/src/handlers/image_generations.rs
atoma-service/src/handlers/mod.rs
atoma-service/src/streamer.rs
atoma-state/Cargo.toml
atoma-state/src/handlers.rs
atoma-state/src/types.rs

Lock the concurrent request counter, so it should never call the claim stack twice.

feat: lock the concurrent request counter

---

Cargo.lock
atoma-service/src/handlers/chat_completions.rs
atoma-service/src/handlers/embeddings.rs
atoma-service/src/handlers/image_generations.rs
atoma-service/src/handlers/mod.rs
atoma-service/src/streamer.rs
atoma-state/Cargo.toml
atoma-state/src/handlers.rs
atoma-state/src/types.rs

Lock the concurrent request counter, so it should never call the claim stack twice.

feat: lock the concurrent request counter #579

---

Cargo.lock
atoma-state/src/handlers.rs

Fix the concurrency issue where the lock is dropped before the DB is updated for concurrent requests.

fix: concurrent release lock too soon

---

atoma-bin/atoma_node.rs
atoma-service/src/config.rs
atoma-service/src/handlers/metrics.rs
atoma-service/src/handlers/mod.rs
atoma-service/src/handlers/request_model.rs
atoma-service/src/lib.rs
config.example.toml

Through our tests we found that  prometheus was failing to query the vllm for metrics, this is because for each request prometheus had to run a query to find the availability of the last 30 seconds. This is unreasonable because realistically this statistic would only update at less frequent intervals, and so we could just use the recently cached value.
So we run the metrics as a background task that updates this cache regularly. If no error is returned we proceed with the chat completion request.

fix: add prom metrics querying to background tasks

---

atoma-daemon/src/telemetry.rs
atoma-service/src/handlers/chat_completions.rs
atoma-service/src/handlers/completions.rs

So that we can identify particular errors from vLLM instances.  Ideally the repetitve nature of this code could be refactored but it's a bit tricky given we consume the response later down in the control flow. So it would be a larger refactor.

chore: attempt to parse error messages

---

Cargo.lock
Cargo.toml
atoma-service/Cargo.toml
atoma-service/src/handlers/mod.rs

Metrics are now not periodic, but on each request, directly from the inference service. We don't use TTFT or queue time anymore. Just the number of running and number of queued requests.

feat: get metrics directly

---

atoma-service/src/middleware.rs

The token estimation on `Completion` was not triggered because it was marked as `NonInference`

fix: completions estimations not triggered

---

atoma-bin/atoma_node.rs
atoma-service/src/config.rs
atoma-service/src/handlers/chat_completions.rs
atoma-service/src/handlers/completions.rs
atoma-service/src/handlers/mod.rs
atoma-service/src/handlers/request_batcher.rs
atoma-service/src/server.rs
atoma-service/src/tests.rs
config.example.toml

This pull request introduces a new batching mechanism for inference requests to improve performance and scalability. The changes include adding a `RequestsBatcher` component, modifying the `AppState` to include the batching sender, and updating request handling logic in the `chat_completions` and `completions` handlers to use the batching mechanism instead of direct HTTP calls.

feat: requests batcher

---

atoma-service/src/handlers/mod.rs

This pull request refactors the handling of metrics in the `inference_service_metrics` module within the `atoma-service/src/handlers/mod.rs` file. The changes reorganize the logic for incrementing the number of running requests and improve the flow for processing metrics.

fix: the number of running requests
