atoma-event-subscribe/sui/src/subscriber.rs, atoma-input-manager/src/lib.rs
Do not crash on input error (e.g. timeout)
Solves #140
=> fix: no crash on input error

atoma-client/src/client.rs, atoma-event-subscribe/sui/Cargo.toml, atoma-event-subscribe/sui/src/main.rs, atoma-event-subscribe/sui/src/subscriber.rs, atoma-inference/src/models/candle/flux.rs, atoma-inference/src/models/candle/stable_diffusion.rs, atoma-inference/src/models/types.rs, atoma-inference/src/service.rs, atoma-inference/src/tests/mod.rs, atoma-input-manager/src/firebase/mod.rs, atoma-input-manager/src/lib.rs, atoma-output-manager/src/firebase/mod.rs, atoma-output-manager/src/gateway/mod.rs, atoma-types/src/lib.rs
Add support for chat, the tokens are downloaded/uploaded to firebase
=> feat: add support for chat feature

.env.example, .gitignore, README.md, docker-compose.yaml
=> feat: vllm docker compose

atoma-sui/src/config.rs
Add `Clone` derive to `AtomaSuiConfig`.
=> feat: add clone to atoma sui config

.dockerignore, .env.example, .gitignore, Cargo.lock, Cargo.toml, Dockerfile, atoma-bin/atoma_daemon.rs, atoma-bin/atoma_node.rs, atoma-daemon/src/daemon.rs, atoma-daemon/src/lib.rs, atoma-service/Cargo.toml, atoma-service/src/tests.rs, atoma-state/src/state_manager.rs, config.example.toml, docker-compose.yaml, entrypoint.sh
This PR introduces several updates and improvements across the Atoma project, including configuration changes, dependency updates, and refinements to logging and daemon handling.
1. **Configuration and Dependencies**:
- Added `cursor.toml` to `.gitignore`.
- Introduced a new dependency on `atoma-daemon` in `Cargo.toml` and `Cargo.lock` to support daemon operations.
2. **Dockerfile and Docker-Compose**:
- Removed `BINARY` build arguments in the Dockerfile, simplifying the build setup.
3. **Code Enhancements**:
- Refactored database URL handling by passing it as a reference to improve memory usage.
- Updated logging configuration to separate `atoma-node` and `atoma-daemon` logs, creating two distinct log files (`atoma-node.log` and `atoma-daemon.log`) with individual JSON formatters.
- …
=> feat: docker daemon revision

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, atoma-bin/atoma_daemon.rs, atoma-bin/atoma_node.rs, atoma-daemon/Cargo.toml, atoma-daemon/src/daemon.rs, atoma-service/Cargo.toml, atoma-service/docs/openapi.yml, atoma-service/src/middleware.rs, atoma-service/src/server.rs, atoma-service/src/streamer.rs, atoma-sui/src/events.rs, atoma-utils/Cargo.toml, atoma-utils/src/lib.rs
now there is global shutdown
- it's triggered when one of the task fails, or ctrl_c is pressed
- it will properly shutdown other tasks
=> fix: proper shutdown/failure

atoma-bin/atoma_node.rs, atoma-service/Cargo.toml, atoma-service/src/middleware.rs, atoma-service/src/server.rs, atoma-service/src/tests.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20241121103103_create_node_tables.sql, atoma-state/src/state_manager.rs, atoma-state/src/types.rs, atoma-sui/src/client.rs, atoma-sui/src/events.rs, atoma-sui/src/subscriber.rs
=> feat: add blockchain query for newly created stacks that are requested to the atoma service

Cargo.lock, Cargo.toml, Dockerfile
Also updated the rust version in the Dockerfile
=> feat: point to a well defined sui sdk release

atoma-confidential/src/key_management.rs, atoma-service/src/tests.rs, atoma-state/src/handlers.rs, atoma-sui/src/events.rs, atoma-sui/src/subscriber.rs
Add timestamp to stack create/settler, it's for the dashboard.
=> feat: add sui timestamp, to stack create/settle

atoma-sui/src/client.rs
Fix the node registration, is not up to date with current contract code.
=> fix: node registration

atoma-bin/atoma_node.rs, atoma-confidential/src/key_management.rs, atoma-confidential/src/service.rs
=> feat: remove file storing for symmetric key and submit rotate key on node start

atoma-daemon/docs/openapi.yml, atoma-daemon/src/handlers/nodes.rs, atoma-daemon/src/types.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20241121103103_create_node_tables.sql, atoma-state/src/state_manager.rs, atoma-state/src/types.rs, atoma-sui/src/client.rs, atoma-sui/src/events.rs, atoma-sui/src/subscriber.rs
See https://github.com/atoma-network/atoma-contracts/pull/124
=> feat: update node logic from contract updates

.env.example, docker-compose.yaml
=> feat: vllm increased customization

atoma-state/src/migrations/20241121103103_create_node_tables.sql, atoma-state/src/migrations/20241226222104_remove_foreign_keys.sql
These are not necessary, as this logic is already handled through the smart contract
=> feat: remove foreign keys

atoma-service/docs/openapi.yml, atoma-service/src/handlers/chat_completions.rs, atoma-service/src/handlers/embeddings.rs, atoma-service/src/handlers/image_generations.rs, atoma-service/src/handlers/mod.rs, atoma-service/src/middleware.rs, atoma-service/src/streamer.rs, atoma-state/src/handlers.rs, atoma-utils/src/lib.rs
=> feat: refactor update compute units logical flow

.env.example, .github/workflows/release.yml, Dockerfile, atoma-confidential/src/service.rs, atoma-confidential/src/tdx.rs
Also adds an option to build with feature `tdx`, through docker-compose
=> feat: resolve some build issues when --features tdx is on

atoma-service/src/streamer.rs
=> feat: add signature and response to every streaming chunk

README.md
These changes are minor markdown edits + the results of my experiencing setting up a running docker instance of an Atoma node
Depends on https://github.com/atoma-network/atoma-contracts/pull/132
=> docs: update `README` with further instructions for setup

prometheus.yml
Add vllm to prometheus
This PR closes #417
=> feat: add vllm to prometheus

docker-compose.dev.yaml
Related to work being done on https://github.com/atoma-network/atoma-testground
This work presumes a sui config being created in the CI workflow prior to composing this file
=> build: add dev compose config

atoma-daemon/src/telemetry.rs, atoma-p2p/src/service.rs
=> fix: temporarily remove outgoing connection log

.env.example, Dockerfile, README.md, atoma-p2p-tester/Dockerfile, atoma-p2p-tester/docker-compose.yml, docker-compose.yaml
A continuation of the work done in https://github.com/atoma-network/atoma-proxy/pull/318
=> chore: add atoma log levels flags

atoma-service/src/middleware.rs
Add `err` to `instrument` in middleware
=> feat: add err to instrument in middleware

atoma-daemon/docs/openapi.yml
=> chore: openapi update router

Cargo.lock, Cargo.toml
=> chore: bump sui version

atoma-service/src/handlers/chat_completions.rs, atoma-service/src/handlers/embeddings.rs, atoma-service/src/handlers/image_generations.rs, atoma-service/src/handlers/metrics.rs, atoma-service/src/streamer.rs
- Closes https://github.com/atoma-network/atoma-node/issues/553
=> feat: add confidential and non-confidential latency metrics

atoma-service/src/streamer.rs
Handling each chunk produces logs, that's way too much
=> chore: polluted logs

atoma-service/src/handlers/mod.rs
=> feat: join metric queries for prometheus into one

atoma-service/src/handlers/mod.rs
The order of job and url is the other way around
=> fix: get_metrics job url order

docker-compose.yaml, prometheus.yml
Related to https://github.com/atoma-network/atoma-proxy/pull/456
=> feat: add node exporter for observability

atoma-bin/atoma_node.rs, atoma-p2p/src/constants.rs, atoma-service/src/config.rs, atoma-service/src/handlers/chat_completions.rs, atoma-service/src/handlers/completions.rs, atoma-service/src/handlers/embeddings.rs, atoma-service/src/handlers/image_generations.rs, atoma-service/src/handlers/metrics.rs, atoma-service/src/handlers/mod.rs, atoma-service/src/middleware.rs, atoma-service/src/server.rs, atoma-service/src/streamer.rs, atoma-service/src/tests.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20250430080652_fiat_balance.sql, atoma-state/src/state_manager.rs, atoma-state/src/types.rs, config.example.toml
Add fiat request for allowed sui addresses.
=> feat: add fiat support

atoma-service/docs/openapi.yml, atoma-service/src/handlers/chat_completions.rs, atoma-service/src/handlers/completions.rs, atoma-service/src/handlers/embeddings.rs, atoma-service/src/handlers/image_generations.rs, atoma-service/src/handlers/mod.rs, atoma-service/src/handlers/request_model.rs, atoma-service/src/middleware.rs, atoma-service/src/streamer.rs, atoma-service/src/tests.rs, atoma-state/src/handlers.rs, atoma-state/src/migrations/20250514211804_split-tokens.sql, atoma-state/src/state_manager.rs, atoma-state/src/types.rs
Split tokens in the fiat table to input/output tokens.
=> feat: split tokens to input output

atoma-service/src/streamer.rs, atoma-state/src/handlers.rs, atoma-state/src/types.rs
=> fix: remove total hash

atoma-service/src/streamer.rs
The last chunk is the one with usage info
=> fix: streamer last chunk recognition

atoma-bin/atoma_node.rs, atoma-p2p/src/metrics.rs, atoma-service/src/config.rs, atoma-service/src/handlers/chat_completions.rs, atoma-service/src/handlers/completions.rs, atoma-service/src/handlers/embeddings.rs, atoma-service/src/handlers/image_generations.rs, atoma-service/src/handlers/mod.rs, atoma-service/src/handlers/request_counter.rs, atoma-service/src/server.rs, atoma-service/src/streamer.rs, atoma-service/src/tests.rs, config.example.toml
Keep the number of running requests.
In follow PR it will be use instead of metrics.
=> feat: num of reqs runnings

atoma-service/src/handlers/chat_completions.rs, atoma-service/src/handlers/completions.rs, atoma-service/src/handlers/embeddings.rs, atoma-service/src/handlers/image_generations.rs, atoma-service/src/handlers/mod.rs, atoma-service/src/handlers/request_counter.rs
Fix the concurrent requests counter, making sure the counter is never above the max.
=> fix: concurrent requests max

atoma-bin/atoma_node.rs, atoma-service/src/config.rs, atoma-service/src/handlers/chat_completions.rs, atoma-service/src/handlers/completions.rs, atoma-service/src/handlers/mod.rs, atoma-service/src/handlers/request_counter.rs, atoma-service/src/server.rs, atoma-service/src/streamer.rs, atoma-service/src/tests.rs, config.example.toml
Add request runinng cap by counting the request ourselfs.
=> feat: add request running cap
